id: PE3E2AC43
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS68018
  title: ཞལ་གདམས་དང་མགུར་གླུ་གཅེས་བཏུས།
  volumes:
    3715f97e785f43438808c56bb421f776:
      image_group_id: I8LS68020
      title: ''
      base_file: v001.txt
  author: ''
